Repository snuailab/waffle_hub, pull requests merged in 2023-05, with the labels that each got.

#94 fix image_size comparsion
  waffle_hub/hub/adapter/hugging_face/train_input_helper.py
Labels: defect

#97 fix huggingface augmentation
  waffle_hub/hub/adapter/hugging_face/train_input_helper.py
Labels: defect

#93 `0.2.0` release
  requirements.txt
  tests/test_dataset.py
  tests/test_hub.py
  waffle_hub/__init__.py
  waffle_hub/dataset/adapter/coco.py
  waffle_hub/dataset/adapter/yolo.py
  waffle_hub/dataset/dataset.py
  waffle_hub/hub/adapter/hugging_face/hugging_face_hub.py
  waffle_hub/hub/adapter/hugging_face/train_input_helper.py
  waffle_hub/hub/adapter/ultralytics/ultralytics_hub.py
  waffle_hub/hub/base_hub.py
  waffle_hub/hub/model/wrapper.py
  waffle_hub/schema/base_schema.py
  waffle_hub/schema/configs.py
  waffle_hub/schema/evaluate.py
  waffle_hub/schema/fields/annotation.py
  waffle_hub/schema/fields/base_field.py
  waffle_hub/schema/fields/category.py
  waffle_hub/schema/fields/image.py
  waffle_hub/utils/callback.py
  waffle_hub/utils/conversion.py
  waffle_hub/utils/draw.py
  waffle_hub/utils/evaluate.py
Labels: release

#118 Check file paths are valid in yolo export
  waffle_hub/dataset/adapter/yolo.py
  waffle_hub/dataset/dataset.py
Labels: defect

#128 reduce: large dataset computational time cost
  waffle_hub/__init__.py
  waffle_hub/dataset/dataset.py
Labels: defect

#127 add Split Method
  waffle_hub/__init__.py
  waffle_hub/dataset/dataset.py
Labels: defect, enhancement

#125 implement cli tool
  setup.py
  tests/test_cli.py
  waffle_hub/run.py
Labels: enhancement
