Repository snuailab/waffle_hub, pull requests merged in 2023-04, with the labels that each got.

#36 Add Experimental model serving
  docs/experimental/model_serve.md
  mkdocs.yml
  waffle_hub/experimental/__init__.py
  waffle_hub/experimental/serve.py
Labels: enhancement

#45 (experimental) add autolabel using GroundingDINO
  docs/experimental/auto_labeling.md
  mkdocs.yml
  waffle_hub/experimental/auto_label/README.md
  waffle_hub/experimental/auto_label/__init__.py
  waffle_hub/experimental/auto_label/grounding_dino.py
Labels: experimental

#61 Hotfix split dataset
  requirements.txt
  tests/test_dataset.py
  waffle_hub/dataset/dataset.py
Labels: defect

#65 tx model hub update
  tests/test_hub.py
  waffle_hub/hub/adapter/tx_model/configs/data_cfg.py
  waffle_hub/hub/adapter/tx_model/configs/model_cfg.py
  waffle_hub/hub/adapter/tx_model/tx_model_hub.py
Labels: defect, enhancement

#59 add Hugging Face
  .github/workflows/ci.yaml
  requirements.txt
  tests/test_dataset.py
  tests/test_hub.py
  waffle_hub/__init__.py
  waffle_hub/dataset/adapter/__init__.py
  waffle_hub/dataset/adapter/huggingface.py
  waffle_hub/dataset/dataset.py
  waffle_hub/hub/adapter/hugging_face/__init__.py
  waffle_hub/hub/adapter/hugging_face/hugging_face_hub.py
  waffle_hub/hub/adapter/hugging_face/train_input_helper.py
Labels: enhancement

#70 hotfix training failed
  waffle_hub/hub/adapter/tx_model/tx_model_hub.py
Labels: defect

#71 From yolo
  tests/conftest.py
  tests/test_dataset.py
  waffle_hub/dataset/dataset.py
Labels: enhancement

#73 add small model in hugging face
  tests/test_hub.py
  waffle_hub/hub/adapter/hugging_face/hugging_face_hub.py
  waffle_hub/hub/adapter/hugging_face/train_input_helper.py
Labels: enhancement

#77 Import split coco
  .pre-commit-config.yaml
  requirements.txt
  tests/test_dataset.py
  waffle_hub/dataset/dataset.py
Labels: enhancement
